name: Deploy to EKS

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker image tag (e.g. v3.2.5)"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Setup kubeconfig
        run: echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig

      - name: Deploy to EKS
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig
        run: |
          kubectl set image deployment/devops-app \
          devops-app=2024tm93728/aceest-app:${{ github.event.inputs.tag }}
